return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    defaults = {
      mode = "n",
      prefix = "<leader>",
    },
    preset = "helix",
    spec = {
      { "<leader>s", group = "Search", mode = { "n", "v" } },
      { "<leader>sd", group = "Diagnostic", mode = { "n" } },
      { "<leader>sg", group = "Git", mode = { "n" } },
      { "<leader>a", group = "Tabs" },
      { "<leader>am", group = "Move" },
      { "<leader>b", group = "Buffer" },
      { "<leader>c", group = "Snacks" },
      { "<leader>d", group = "Debug" },
      { "<leader>g", group = "Git", mode = { "n", "v" } },
      { "<leader>w", group = "Window" },
      { "<leader>l", group = "LSP" },
      { "<leader>wd", group = "Delete" },
      { "<leader>t", group = "Terminal" },
      { "<leader>u", group = "Toggle functions" },
      { "<leader>x", group = "Dagnostic" },
      { "<leader>j", group = "Notes" },
      { "<leader>js", group = "Search" },
      { "<leader>m", group = "Miscellaneous" },
      { "<leader> ", group = "Behave" },
    },
    win = {
      padding = { 2, 2, 2, 2 },
      border = "rounded",
    },
  },
}
